name: Node.js CI with Docker Build, Test, and Push

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]  # Specify Node.js versions to test

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Install Node.js and npm
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run ESLint
      - name: Run Linter
        run: npx eslint .
        # ESLint is a static code analysis tool for identifying problematic patterns in JavaScript.

      # Step 6: Set executable permissions for Jest (if needed)
      - name: Set executable permissions for Jest
        run: chmod +x node_modules/.bin/jest

      # Step 7: Run tests with Jest
      - name: Run tests with Jest
        run: npm run test

      # Step 8: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t adebayo2007/devops:${{ github.sha }} .
          docker tag adebayo2007/devops:${{ github.sha }} adebayo2007/devops:latest

      # Step 9: Log in to Docker Hub using access token from GitHub secret
      - name: Log in to Docker Hub
        run: echo "${{ secrets.CALCULATOR }}" | docker login -u adebayo2007 --password-stdin

      # Step 10: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push adebayo2007/devops:${{ github.sha }}
          docker push adebayo2007/devops:latest

  # Step 11: Bump version and tag (runs only on push to main branch)
  bump-version-and-tag:
    name: Bump version and tag
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        # Automatic version bumping and tagging based on push events to main branch.

  # Step 12: Create GitHub release (runs on tag push)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
  
  # Step 13: Deploy to AWS (runs only on push to main branch)
  deploy-to-aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
        # Configures AWS credentials for deployment.

      - name: Deploy to AWS
        run: |
          # Add your deployment script here.
          # For example, using AWS CLI commands to deploy.
