name: Node.js CI with Docker Build, Test, and Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      # Set executable permissions for Jest (if needed)
      - name: Set executable permissions for Jest
        run: chmod +x node_modules/.bin/jest

      # Run tests with Jest
      - name: Run tests with Jest
        run: npm run test

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t adebayo2007/devops:${{ github.sha }} .
          docker tag adebayo2007/devops:${{ github.sha }} adebayo2007/devops:latest

      # Log in to Docker Hub using access token from GitHub secret
      - name: Log in to Docker Hub
        run: echo "${{ secrets.CALCULATOR }}" | docker login -u adebayo2007 --password-stdin

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push adebayo2007/devops:${{ github.sha }}
          docker push adebayo2007/devops:latest
